//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker
{
    public partial class DockerVersionTask : ExternalProcessTaskBase<int, DockerVersionTask>
    {
        public DockerVersionTask()
        {
            ExecutablePath = "docker";
            WithArguments("version");
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Format the output using the given Go template
        /// </summary>
        [ArgKey("--format")]
        public DockerVersionTask Format(string format)
        {
            WithArgumentsKeyFromAttribute(format.ToString());
            return this;
        }

        /// <summary>
        /// Kubernetes config file
        /// </summary>
        [ArgKey("--kubeconfig")]
        public DockerVersionTask Kubeconfig(string kubeconfig)
        {
            WithArgumentsKeyFromAttribute(kubeconfig.ToString());
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            return base.DoExecute(context);
        }
    }
}