//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker
{
    public partial class DockerStartTask : ExternalProcessTaskBase<int, DockerStartTask>
    {
        private string[] _container;


        public DockerStartTask(params string[] container)
        {
            ExecutablePath = "docker";
            WithArguments("start");
            _container = container;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Attach STDOUT/STDERR and forward signals
        /// </summary>
        [ArgKey("--attach")]
        public DockerStartTask Attach()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Restore from this checkpoint
        /// </summary>
        [ArgKey("--checkpoint")]
        public DockerStartTask Checkpoint(string checkpoint)
        {
            WithArgumentsKeyFromAttribute(checkpoint.ToString());
            return this;
        }

        /// <summary>
        /// Use a custom checkpoint storage directory
        /// </summary>
        [ArgKey("--checkpoint-dir")]
        public DockerStartTask CheckpointDir(string checkpointDir)
        {
            WithArgumentsKeyFromAttribute(checkpointDir.ToString());
            return this;
        }

        /// <summary>
        /// Override the key sequence for detaching a container
        /// </summary>
        [ArgKey("--detach-keys")]
        public DockerStartTask DetachKeys(string detachKeys)
        {
            WithArgumentsKeyFromAttribute(detachKeys.ToString());
            return this;
        }

        /// <summary>
        /// Attach container's STDIN
        /// </summary>
        [ArgKey("--interactive")]
        public DockerStartTask Interactive()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_container);

            return base.DoExecute(context);
        }
    }
}