//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker
{
    public partial class DockerExecTask : ExternalProcessTaskBase<int, DockerExecTask>
    {
        private string _container;
        private string _command;
        private string[] _arg;


        public DockerExecTask(string container, string command, params string[] arg)
        {
            ExecutablePath = "docker";
            WithArguments("exec");
            _container = container;
            _command = command;
            _arg = arg;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Detached mode: run command in the background
        /// </summary>
        [ArgKey("--detach")]
        public DockerExecTask Detach()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Override the key sequence for detaching a container
        /// </summary>
        [ArgKey("--detach-keys")]
        public DockerExecTask DetachKeys(string detachKeys)
        {
            WithArgumentsKeyFromAttribute(detachKeys.ToString());
            return this;
        }

        /// <summary>
        /// Set environment variables
        /// </summary>
        [ArgKey("--env")]
        public DockerExecTask Env(string env)
        {
            WithArgumentsKeyFromAttribute(env.ToString());
            return this;
        }

        /// <summary>
        /// Keep STDIN open even if not attached
        /// </summary>
        [ArgKey("--interactive")]
        public DockerExecTask Interactive()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Give extended privileges to the command
        /// </summary>
        [ArgKey("--privileged")]
        public DockerExecTask Privileged()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Allocate a pseudo-TTY
        /// </summary>
        [ArgKey("--tty")]
        public DockerExecTask Tty()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Username or UID (format: <name|uid>[:<group|gid>])
        /// </summary>
        [ArgKey("--user")]
        public DockerExecTask User(string user)
        {
            WithArgumentsKeyFromAttribute(user.ToString());
            return this;
        }

        /// <summary>
        /// Working directory inside the container
        /// </summary>
        [ArgKey("--workdir")]
        public DockerExecTask Workdir(string workdir)
        {
            WithArgumentsKeyFromAttribute(workdir.ToString());
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_container);
            WithArguments(_command);
            WithArguments(_arg);

            return base.DoExecute(context);
        }
    }
}