//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker
{
    public partial class DockerSearchTask : ExternalProcessTaskBase<int, DockerSearchTask>
    {
        private string _term;


        public DockerSearchTask(string term)
        {
            ExecutablePath = "docker";
            WithArguments("search");
            _term = term;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Only show automated builds
        /// </summary>
        [ArgKey("--automated")]
        public DockerSearchTask Automated()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Filter output based on conditions provided
        /// </summary>
        [ArgKey("--filter")]
        public DockerSearchTask Filter(string filter)
        {
            WithArgumentsKeyFromAttribute(filter.ToString());
            return this;
        }

        /// <summary>
        /// Pretty-print search using a Go template
        /// </summary>
        [ArgKey("--format")]
        public DockerSearchTask Format(string format)
        {
            WithArgumentsKeyFromAttribute(format.ToString());
            return this;
        }

        /// <summary>
        /// Max number of search results
        /// </summary>
        [ArgKey("--limit")]
        public DockerSearchTask Limit(int limit)
        {
            WithArgumentsKeyFromAttribute(limit.ToString());
            return this;
        }

        /// <summary>
        /// Don't truncate output
        /// </summary>
        [ArgKey("--no-trunc")]
        public DockerSearchTask NoTrunc()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Only displays with at least x stars
        /// </summary>
        [ArgKey("--stars")]
        public DockerSearchTask Stars(uint stars)
        {
            WithArgumentsKeyFromAttribute(stars.ToString());
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_term);

            return base.DoExecute(context);
        }
    }
}