<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <PackAsTool>true</PackAsTool>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <ToolCommandName>flubu</ToolCommandName>
    <PackageTags>dotnet;flubu;flubucore;build;builder;script;buildscript;automation;VisualStudio</PackageTags>
    <Authors>Marko Zorec;Zoro Zorec;</Authors>
    <PackageLicenseUrl>https://opensource.org/licenses/MIT</PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/dotnetcore/FlubuCore</PackageProjectUrl>
    <PackageReleaseNotes>https://github.com/dotnetcore/FlubuCore/blob/master/CHANGELOG.md</PackageReleaseNotes>
    <Description>
      This package includes the flubu local / global tool for executing FlubuCore scripts.

      FlubuCore is a cross platform build and deployment automation system for building projects and executing deployment scripts using C# code.

      Documentation can be found at: https://github.com/dotnetcore/FlubuCore

      Detailed examples can be found at: https://github.com/dotnetcore/FlubuCore.Examples
    </Description>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <AssemblyVersion>10.0.1.0</AssemblyVersion>
    <FileVersion>10.0.1.0</FileVersion>
    <Version>10.0.1</Version>
    <CodeAnalysisRuleSet>..\stylecop.ruleset</CodeAnalysisRuleSet>
    <NoWarn>1701;1702;1705;1591;1573;1572;1574</NoWarn>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlubuCore\FlubuCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
