//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Plugin
{
    public partial class DockerPluginUpgradeTask : ExternalProcessTaskBase<int, DockerPluginUpgradeTask>
    {
        private string _plugin;
        private string _remote;


        public DockerPluginUpgradeTask(string plugin, string remote = null)
        {
            ExecutablePath = "docker";
            WithArguments("plugin upgrade");
            _plugin = plugin;
            _remote = remote;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Skip image verification
        /// </summary>
        [ArgKey("--disable-content-trust")]
        public DockerPluginUpgradeTask DisableContentTrust()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Grant all permissions necessary to run the plugin
        /// </summary>
        [ArgKey("--grant-all-permissions")]
        public DockerPluginUpgradeTask GrantAllPermissions()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Do not check if specified remote plugin matches existing plugin image
        /// </summary>
        [ArgKey("--skip-remote-check")]
        public DockerPluginUpgradeTask SkipRemoteCheck()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_plugin);
            WithArguments(_remote);

            return base.DoExecute(context);
        }
    }
}