//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Volume
{
    public partial class DockerVolumePruneTask : ExternalProcessTaskBase<int, DockerVolumePruneTask>
    {
        public DockerVolumePruneTask()
        {
            ExecutablePath = "docker";
            WithArguments("volume prune");
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Provide filter values (e.g. 'label=<label>')
        /// </summary>
        [ArgKey("--filter")]
        public DockerVolumePruneTask Filter(string filter)
        {
            WithArgumentsKeyFromAttribute(filter.ToString());
            return this;
        }

        /// <summary>
        /// Do not prompt for confirmation
        /// </summary>
        [ArgKey("--force")]
        public DockerVolumePruneTask Force()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            return base.DoExecute(context);
        }
    }
}