//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Volume
{
    public partial class DockerVolumeLsTask : ExternalProcessTaskBase<int, DockerVolumeLsTask>
    {
        public DockerVolumeLsTask()
        {
            ExecutablePath = "docker";
            WithArguments("volume ls");
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Provide filter values (e.g. 'dangling=true')
        /// </summary>
        [ArgKey("--filter")]
        public DockerVolumeLsTask Filter(string filter)
        {
            WithArgumentsKeyFromAttribute(filter.ToString());
            return this;
        }

        /// <summary>
        /// Pretty-print volumes using a Go template
        /// </summary>
        [ArgKey("--format")]
        public DockerVolumeLsTask Format(string format)
        {
            WithArgumentsKeyFromAttribute(format.ToString());
            return this;
        }

        /// <summary>
        /// Only display volume names
        /// </summary>
        [ArgKey("--quiet")]
        public DockerVolumeLsTask Quiet()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            return base.DoExecute(context);
        }
    }
}