//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Context
{
    public partial class DockerContextRmTask : ExternalProcessTaskBase<int, DockerContextRmTask>
    {
        private string[] _context;


        public DockerContextRmTask(params string[] context)
        {
            ExecutablePath = "docker";
            WithArguments("context rm");
            _context = context;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Force the removal of a context in use
        /// </summary>
        [ArgKey("--force")]
        public DockerContextRmTask Force()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_context);

            return base.DoExecute(context);
        }
    }
}