
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Node;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Node
    {  
        
            public DockerNodeInspectTask NodeInspect(string self ,  params string[] node)
            {
                return new DockerNodeInspectTask(self,  node);
            }

            public DockerNodeLsTask NodeLs()
            {
                return new DockerNodeLsTask();
            }

            public DockerNodePsTask NodePs(params string[] node)
            {
                return new DockerNodePsTask(node);
            }

            public DockerNodeRmTask NodeRm(params string[] node)
            {
                return new DockerNodeRmTask(node);
            }

            public DockerNodeUpdateTask NodeUpdate(string node)
            {
                return new DockerNodeUpdateTask(node);
            }
        
    }
}

