
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Plugin;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Plugin
    {  
        
            public DockerPluginCreateTask PluginCreate(params string[] plugin)
            {
                return new DockerPluginCreateTask(plugin);
            }

            public DockerPluginDisableTask PluginDisable(string plugin)
            {
                return new DockerPluginDisableTask(plugin);
            }

            public DockerPluginEnableTask PluginEnable(string plugin)
            {
                return new DockerPluginEnableTask(plugin);
            }

            public DockerPluginInspectTask PluginInspect(params string[] plugin)
            {
                return new DockerPluginInspectTask(plugin);
            }

            public DockerPluginInstallTask PluginInstall(string plugin)
            {
                return new DockerPluginInstallTask(plugin);
            }

            public DockerPluginLsTask PluginLs()
            {
                return new DockerPluginLsTask();
            }

            public DockerPluginPushTask PluginPush(string plugin)
            {
                return new DockerPluginPushTask(plugin);
            }

            public DockerPluginRmTask PluginRm(params string[] plugin)
            {
                return new DockerPluginRmTask(plugin);
            }

            public DockerPluginUpgradeTask PluginUpgrade(string plugin ,  string remote)
            {
                return new DockerPluginUpgradeTask(plugin,  remote);
            }
        
    }
}

