
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Secret;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Secret
    {  
        
            public DockerSecretCreateTask SecretCreate(string secret ,  string file)
            {
                return new DockerSecretCreateTask(secret,  file);
            }

            public DockerSecretInspectTask SecretInspect(params string[] secret)
            {
                return new DockerSecretInspectTask(secret);
            }

            public DockerSecretLsTask SecretLs()
            {
                return new DockerSecretLsTask();
            }
        
    }
}

