
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Swarm;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Swarm
    {  
        
            public DockerSwarmCaTask SwarmCa()
            {
                return new DockerSwarmCaTask();
            }

            public DockerSwarmInitTask SwarmInit()
            {
                return new DockerSwarmInitTask();
            }

            public DockerSwarmJoinTokenTask SwarmJoinToken(string worker)
            {
                return new DockerSwarmJoinTokenTask(worker);
            }

            public DockerSwarmJoinTask SwarmJoin(string host)
            {
                return new DockerSwarmJoinTask(host);
            }

            public DockerSwarmLeaveTask SwarmLeave()
            {
                return new DockerSwarmLeaveTask();
            }

            public DockerSwarmUnlockKeyTask SwarmUnlockKey()
            {
                return new DockerSwarmUnlockKeyTask();
            }

            public DockerSwarmUpdateTask SwarmUpdate()
            {
                return new DockerSwarmUpdateTask();
            }
        
    }
}

