
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Volume;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Volume
    {  
        
            public DockerVolumeCreateTask VolumeCreate(string volume)
            {
                return new DockerVolumeCreateTask(volume);
            }

            public DockerVolumeInspectTask VolumeInspect(params string[] volume)
            {
                return new DockerVolumeInspectTask(volume);
            }

            public DockerVolumeLsTask VolumeLs()
            {
                return new DockerVolumeLsTask();
            }

            public DockerVolumePruneTask VolumePrune()
            {
                return new DockerVolumePruneTask();
            }

            public DockerVolumeRmTask VolumeRm(params string[] volume)
            {
                return new DockerVolumeRmTask(volume);
            }
        
    }
}

