//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Trust
{
    public partial class DockerTrustRevokeTask : ExternalProcessTaskBase<int, DockerTrustRevokeTask>
    {
        private string _image;


        public DockerTrustRevokeTask(string image)
        {
            ExecutablePath = "docker";
            WithArguments("trust revoke");
            _image = image;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Do not prompt for confirmation
        /// </summary>
        [ArgKey("--yes")]
        public DockerTrustRevokeTask Yes()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_image);

            return base.DoExecute(context);
        }
    }
}