//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Config
{
    public partial class DockerConfigInspectTask : ExternalProcessTaskBase<int, DockerConfigInspectTask>
    {
        private string[] _config;


        public DockerConfigInspectTask(params string[] config)
        {
            ExecutablePath = "docker";
            WithArguments("config inspect");
            _config = config;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Format the output using the given Go template
        /// </summary>
        [ArgKey("--format")]
        public DockerConfigInspectTask Format(string format)
        {
            WithArgumentsKeyFromAttribute(format.ToString());
            return this;
        }

        /// <summary>
        /// Print the information in a human friendly format
        /// </summary>
        [ArgKey("--pretty")]
        public DockerConfigInspectTask Pretty()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_config);

            return base.DoExecute(context);
        }
    }
}