//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Swarm
{
    public partial class DockerSwarmCaTask : ExternalProcessTaskBase<int, DockerSwarmCaTask>
    {
        public DockerSwarmCaTask()
        {
            ExecutablePath = "docker";
            WithArguments("swarm ca");
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Path to the PEM-formatted root CA certificate to use for the new cluster
        /// </summary>
        [ArgKey("--ca-cert")]
        public DockerSwarmCaTask CaCert(string caCert)
        {
            WithArgumentsKeyFromAttribute(caCert.ToString());
            return this;
        }

        /// <summary>
        /// Path to the PEM-formatted root CA key to use for the new cluster
        /// </summary>
        [ArgKey("--ca-key")]
        public DockerSwarmCaTask CaKey(string caKey)
        {
            WithArgumentsKeyFromAttribute(caKey.ToString());
            return this;
        }

        /// <summary>
        /// Validity period for node certificates (ns|us|ms|s|m|h)
        /// </summary>
        [ArgKey("--cert-expiry")]
        public DockerSwarmCaTask CertExpiry(string certExpiry)
        {
            WithArgumentsKeyFromAttribute(certExpiry.ToString());
            return this;
        }

        /// <summary>
        /// Exit immediately instead of waiting for the root rotation to converge
        /// </summary>
        [ArgKey("--detach")]
        public DockerSwarmCaTask Detach()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Specifications of one or more certificate signing endpoints
        /// </summary>
        [ArgKey("--external-ca")]
        public DockerSwarmCaTask ExternalCa(string externalCa)
        {
            WithArgumentsKeyFromAttribute(externalCa.ToString());
            return this;
        }

        /// <summary>
        /// Suppress progress output
        /// </summary>
        [ArgKey("--quiet")]
        public DockerSwarmCaTask Quiet()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Rotate the swarm CA - if no certificate or key are provided, new ones will be generated
        /// </summary>
        [ArgKey("--rotate")]
        public DockerSwarmCaTask Rotate()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            return base.DoExecute(context);
        }
    }
}