
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Builder;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Builder
    {  
        
            public DockerBuilderBuildTask BuilderBuild(string pathOrURL)
            {
                return new DockerBuilderBuildTask(pathOrURL);
            }

            public DockerBuilderPruneTask BuilderPrune()
            {
                return new DockerBuilderPruneTask();
            }
        
    }
}

