
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Config;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Config
    {  
        
            public DockerConfigCreateTask ConfigCreate(string config ,  string file)
            {
                return new DockerConfigCreateTask(config,  file);
            }

            public DockerConfigInspectTask ConfigInspect(params string[] config)
            {
                return new DockerConfigInspectTask(config);
            }

            public DockerConfigLsTask ConfigLs()
            {
                return new DockerConfigLsTask();
            }
        
    }
}

