
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Network;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Network
    {  
        
            public DockerNetworkConnectTask NetworkConnect(string network ,  string container)
            {
                return new DockerNetworkConnectTask(network,  container);
            }

            public DockerNetworkCreateTask NetworkCreate(string network)
            {
                return new DockerNetworkCreateTask(network);
            }

            public DockerNetworkDisconnectTask NetworkDisconnect(string network ,  string container)
            {
                return new DockerNetworkDisconnectTask(network,  container);
            }

            public DockerNetworkInspectTask NetworkInspect(params string[] network)
            {
                return new DockerNetworkInspectTask(network);
            }

            public DockerNetworkLsTask NetworkLs()
            {
                return new DockerNetworkLsTask();
            }

            public DockerNetworkPruneTask NetworkPrune()
            {
                return new DockerNetworkPruneTask();
            }
        
    }
}

