
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Stack;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Stack
    {  
        
            public DockerStackDeployTask StackDeploy(string stack)
            {
                return new DockerStackDeployTask(stack);
            }

            public DockerStackLsTask StackLs()
            {
                return new DockerStackLsTask();
            }

            public DockerStackPsTask StackPs(string stack)
            {
                return new DockerStackPsTask(stack);
            }

            public DockerStackServicesTask StackServices(string stack)
            {
                return new DockerStackServicesTask(stack);
            }
        
    }
}

