
//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Tasks.Docker.Trust;

namespace FlubuCore.Context.FluentInterface.Docker
{
    public class Trust
    {  
        
            public DockerTrustInspectTask TrustInspect(params string[] image)
            {
                return new DockerTrustInspectTask(image);
            }

            public DockerTrustKeyGenerateTask TrustKeyGenerate(string name)
            {
                return new DockerTrustKeyGenerateTask(name);
            }

            public DockerTrustKeyLoadTask TrustKeyLoad(string keyfile)
            {
                return new DockerTrustKeyLoadTask(keyfile);
            }

            public DockerTrustRevokeTask TrustRevoke(string image)
            {
                return new DockerTrustRevokeTask(image);
            }

            public DockerTrustSignTask TrustSign(string image)
            {
                return new DockerTrustSignTask(image);
            }

            public DockerTrustSignerAddTask TrustSignerAdd(string options ,  string name ,  params string[] repository)
            {
                return new DockerTrustSignerAddTask(options,  name,  repository);
            }

            public DockerTrustSignerRemoveTask TrustSignerRemove(string name ,  params string[] repository)
            {
                return new DockerTrustSignerRemoveTask(name,  repository);
            }
        
    }
}

