//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Engine
{
    public partial class DockerEngineCheckTask : ExternalProcessTaskBase<int, DockerEngineCheckTask>
    {
        public DockerEngineCheckTask()
        {
            ExecutablePath = "docker";
            WithArguments("engine check");
        }

        protected override string Description { get; set; }

        /// <summary>
        /// override default location of containerd endpoint
        /// </summary>
        [ArgKey("--containerd")]
        public DockerEngineCheckTask Containerd(string containerd)
        {
            WithArgumentsKeyFromAttribute(containerd.ToString());
            return this;
        }

        /// <summary>
        /// Report downgrades (default omits older versions)
        /// </summary>
        [ArgKey("--downgrades")]
        public DockerEngineCheckTask Downgrades()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Specify engine image (default uses the same image as currently running)
        /// </summary>
        [ArgKey("--engine-image")]
        public DockerEngineCheckTask EngineImage(string engineImage)
        {
            WithArgumentsKeyFromAttribute(engineImage.ToString());
            return this;
        }

        /// <summary>
        /// Pretty-print updates using a Go template
        /// </summary>
        [ArgKey("--format")]
        public DockerEngineCheckTask Format(string format)
        {
            WithArgumentsKeyFromAttribute(format.ToString());
            return this;
        }

        /// <summary>
        /// Include pre-release versions
        /// </summary>
        [ArgKey("--pre-releases")]
        public DockerEngineCheckTask PreReleases()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Only display available versions
        /// </summary>
        [ArgKey("--quiet")]
        public DockerEngineCheckTask Quiet()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Override the existing location where engine images are pulled
        /// </summary>
        [ArgKey("--registry-prefix")]
        public DockerEngineCheckTask RegistryPrefix(string registryPrefix)
        {
            WithArgumentsKeyFromAttribute(registryPrefix.ToString());
            return this;
        }

        /// <summary>
        /// Report available upgrades
        /// </summary>
        [ArgKey("--upgrades")]
        public DockerEngineCheckTask Upgrades()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            return base.DoExecute(context);
        }
    }
}