//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Stack
{
    public partial class DockerStackRmTask : ExternalProcessTaskBase<int, DockerStackRmTask>
    {
        private string[] _stack;


        public DockerStackRmTask(params string[] stack)
        {
            ExecutablePath = "docker";
            WithArguments("stack rm");
            _stack = stack;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Kubernetes namespace to use
        /// </summary>
        [ArgKey("--namespace")]
        public DockerStackRmTask Namespace(string @namespace)
        {
            WithArgumentsKeyFromAttribute(@namespace.ToString());
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_stack);

            return base.DoExecute(context);
        }
    }
}