<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net462</TargetFramework>
    <WarningsAsErrors>true</WarningsAsErrors>
    <AssemblyName>dotnet-flubu</AssemblyName>
    <OutputType>Exe</OutputType>
    <RootNamespace>DotNet.Cli.Flubu</RootNamespace>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <AssemblyVersion>10.0.1.0</AssemblyVersion>
    <FileVersion>10.0.1.0</FileVersion>
    <Version>10.0.1</Version>
    <CodeAnalysisRuleSet>..\stylecop.ruleset</CodeAnalysisRuleSet>
    <NoWarn>1701;1702;1705;1591;1573;1572;1574</NoWarn>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net462'">
    <RuntimeIdentifiers>win7-x64;win7-x86</RuntimeIdentifiers>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net462|AnyCPU'">
    <DefineConstants>TRACE;NETSTANDARD2_0</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FlubuCore\FlubuCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>
</Project>
