//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Service
{
    public partial class DockerServiceCreateTask : ExternalProcessTaskBase<int, DockerServiceCreateTask>
    {
        private string _image;
        private string _command;
        private string[] _arg;


        public DockerServiceCreateTask(string image, string command = null, params string[] arg)
        {
            ExecutablePath = "docker";
            WithArguments("service create");
            _image = image;
            _command = command;
            _arg = arg;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Specify configurations to expose to the service
        /// </summary>
        [ArgKey("--config")]
        public DockerServiceCreateTask Config(string config)
        {
            WithArgumentsKeyFromAttribute(config.ToString());
            return this;
        }

        /// <summary>
        /// Placement constraints
        /// </summary>
        [ArgKey("--constraint")]
        public DockerServiceCreateTask Constraint(string constraint)
        {
            WithArgumentsKeyFromAttribute(constraint.ToString());
            return this;
        }

        /// <summary>
        /// Container labels
        /// </summary>
        [ArgKey("--container-label")]
        public DockerServiceCreateTask ContainerLabel(string containerLabel)
        {
            WithArgumentsKeyFromAttribute(containerLabel.ToString());
            return this;
        }

        /// <summary>
        /// Credential spec for managed service account (Windows only)
        /// </summary>
        [ArgKey("--credential-spec")]
        public DockerServiceCreateTask CredentialSpec(string credentialSpec)
        {
            WithArgumentsKeyFromAttribute(credentialSpec.ToString());
            return this;
        }

        /// <summary>
        /// Exit immediately instead of waiting for the service to converge
        /// </summary>
        [ArgKey("--detach")]
        public DockerServiceCreateTask Detach()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Set custom DNS servers
        /// </summary>
        [ArgKey("--dns")]
        public DockerServiceCreateTask Dns(string dns)
        {
            WithArgumentsKeyFromAttribute(dns.ToString());
            return this;
        }

        /// <summary>
        /// Set DNS options
        /// </summary>
        [ArgKey("--dns-option")]
        public DockerServiceCreateTask DnsOption(string dnsOption)
        {
            WithArgumentsKeyFromAttribute(dnsOption.ToString());
            return this;
        }

        /// <summary>
        /// Set custom DNS search domains
        /// </summary>
        [ArgKey("--dns-search")]
        public DockerServiceCreateTask DnsSearch(string dnsSearch)
        {
            WithArgumentsKeyFromAttribute(dnsSearch.ToString());
            return this;
        }

        /// <summary>
        /// Endpoint mode (vip or dnsrr)
        /// </summary>
        [ArgKey("--endpoint-mode")]
        public DockerServiceCreateTask EndpointMode(string endpointMode)
        {
            WithArgumentsKeyFromAttribute(endpointMode.ToString());
            return this;
        }

        /// <summary>
        /// Overwrite the default ENTRYPOINT of the image
        /// </summary>
        [ArgKey("--entrypoint")]
        public DockerServiceCreateTask Entrypoint(string entrypoint)
        {
            WithArgumentsKeyFromAttribute(entrypoint.ToString());
            return this;
        }

        /// <summary>
        /// Set environment variables
        /// </summary>
        [ArgKey("--env")]
        public DockerServiceCreateTask Env(string env)
        {
            WithArgumentsKeyFromAttribute(env.ToString());
            return this;
        }

        /// <summary>
        /// Read in a file of environment variables
        /// </summary>
        [ArgKey("--env-file")]
        public DockerServiceCreateTask EnvFile(string envFile)
        {
            WithArgumentsKeyFromAttribute(envFile.ToString());
            return this;
        }

        /// <summary>
        /// User defined resources
        /// </summary>
        [ArgKey("--generic-resource")]
        public DockerServiceCreateTask GenericResource(string genericResource)
        {
            WithArgumentsKeyFromAttribute(genericResource.ToString());
            return this;
        }

        /// <summary>
        /// Set one or more supplementary user groups for the container
        /// </summary>
        [ArgKey("--group")]
        public DockerServiceCreateTask Group(string group)
        {
            WithArgumentsKeyFromAttribute(group.ToString());
            return this;
        }

        /// <summary>
        /// Command to run to check health
        /// </summary>
        [ArgKey("--health-cmd")]
        public DockerServiceCreateTask HealthCmd(string healthCmd)
        {
            WithArgumentsKeyFromAttribute(healthCmd.ToString());
            return this;
        }

        /// <summary>
        /// Time between running the check (ms|s|m|h)
        /// </summary>
        [ArgKey("--health-interval")]
        public DockerServiceCreateTask HealthInterval(string healthInterval)
        {
            WithArgumentsKeyFromAttribute(healthInterval.ToString());
            return this;
        }

        /// <summary>
        /// Consecutive failures needed to report unhealthy
        /// </summary>
        [ArgKey("--health-retries")]
        public DockerServiceCreateTask HealthRetries(int healthRetries)
        {
            WithArgumentsKeyFromAttribute(healthRetries.ToString());
            return this;
        }

        /// <summary>
        /// Start period for the container to initialize before counting retries towards unstable (ms|s|m|h)
        /// </summary>
        [ArgKey("--health-start-period")]
        public DockerServiceCreateTask HealthStartPeriod(string healthStartPeriod)
        {
            WithArgumentsKeyFromAttribute(healthStartPeriod.ToString());
            return this;
        }

        /// <summary>
        /// Maximum time to allow one check to run (ms|s|m|h)
        /// </summary>
        [ArgKey("--health-timeout")]
        public DockerServiceCreateTask HealthTimeout(string healthTimeout)
        {
            WithArgumentsKeyFromAttribute(healthTimeout.ToString());
            return this;
        }

        /// <summary>
        /// Set one or more custom host-to-IP mappings (host:ip)
        /// </summary>
        [ArgKey("--host")]
        public DockerServiceCreateTask Host(string host)
        {
            WithArgumentsKeyFromAttribute(host.ToString());
            return this;
        }

        /// <summary>
        /// Container hostname
        /// </summary>
        [ArgKey("--hostname")]
        public DockerServiceCreateTask Hostname(string hostname)
        {
            WithArgumentsKeyFromAttribute(hostname.ToString());
            return this;
        }

        /// <summary>
        /// Use an init inside each service container to forward signals and reap processes
        /// </summary>
        [ArgKey("--init")]
        public DockerServiceCreateTask Init()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Service container isolation mode
        /// </summary>
        [ArgKey("--isolation")]
        public DockerServiceCreateTask Isolation(string isolation)
        {
            WithArgumentsKeyFromAttribute(isolation.ToString());
            return this;
        }

        /// <summary>
        /// Service labels
        /// </summary>
        [ArgKey("--label")]
        public DockerServiceCreateTask Label(string label)
        {
            WithArgumentsKeyFromAttribute(label.ToString());
            return this;
        }

        /// <summary>
        /// Limit CPUs
        /// </summary>
        [ArgKey("--limit-cpu")]
        public DockerServiceCreateTask LimitCpu(decimal limitCpu)
        {
            WithArgumentsKeyFromAttribute(limitCpu.ToString());
            return this;
        }

        /// <summary>
        /// Limit Memory
        /// </summary>
        [ArgKey("--limit-memory")]
        public DockerServiceCreateTask LimitMemory(string limitMemory)
        {
            WithArgumentsKeyFromAttribute(limitMemory.ToString());
            return this;
        }

        /// <summary>
        /// Logging driver for service
        /// </summary>
        [ArgKey("--log-driver")]
        public DockerServiceCreateTask LogDriver(string logDriver)
        {
            WithArgumentsKeyFromAttribute(logDriver.ToString());
            return this;
        }

        /// <summary>
        /// Logging driver options
        /// </summary>
        [ArgKey("--log-opt")]
        public DockerServiceCreateTask LogOpt(string logOpt)
        {
            WithArgumentsKeyFromAttribute(logOpt.ToString());
            return this;
        }

        /// <summary>
        /// Service mode (replicated or global)
        /// </summary>
        [ArgKey("--mode")]
        public DockerServiceCreateTask Mode(string mode)
        {
            WithArgumentsKeyFromAttribute(mode.ToString());
            return this;
        }

        /// <summary>
        /// Attach a filesystem mount to the service
        /// </summary>
        [ArgKey("--mount")]
        public DockerServiceCreateTask Mount(string mount)
        {
            WithArgumentsKeyFromAttribute(mount.ToString());
            return this;
        }

        /// <summary>
        /// Service name
        /// </summary>
        [ArgKey("--name")]
        public DockerServiceCreateTask Name(string name)
        {
            WithArgumentsKeyFromAttribute(name.ToString());
            return this;
        }

        /// <summary>
        /// Network attachments
        /// </summary>
        [ArgKey("--network")]
        public DockerServiceCreateTask Network(string network)
        {
            WithArgumentsKeyFromAttribute(network.ToString());
            return this;
        }

        /// <summary>
        /// Disable any container-specified HEALTHCHECK
        /// </summary>
        [ArgKey("--no-healthcheck")]
        public DockerServiceCreateTask NoHealthcheck()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Do not query the registry to resolve image digest and supported platforms
        /// </summary>
        [ArgKey("--no-resolve-image")]
        public DockerServiceCreateTask NoResolveImage()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Add a placement preference
        /// </summary>
        [ArgKey("--placement-pref")]
        public DockerServiceCreateTask PlacementPref(string placementPref)
        {
            WithArgumentsKeyFromAttribute(placementPref.ToString());
            return this;
        }

        /// <summary>
        /// Publish a port as a node port
        /// </summary>
        [ArgKey("--publish")]
        public DockerServiceCreateTask Publish(string publish)
        {
            WithArgumentsKeyFromAttribute(publish.ToString());
            return this;
        }

        /// <summary>
        /// Suppress progress output
        /// </summary>
        [ArgKey("--quiet")]
        public DockerServiceCreateTask Quiet()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Mount the container's root filesystem as read only
        /// </summary>
        [ArgKey("--read-only")]
        public DockerServiceCreateTask ReadOnly()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Number of tasks
        /// </summary>
        [ArgKey("--replicas")]
        public DockerServiceCreateTask Replicas(uint replicas)
        {
            WithArgumentsKeyFromAttribute(replicas.ToString());
            return this;
        }

        /// <summary>
        /// Maximum number of tasks per node (default 0 = unlimited)
        /// </summary>
        [ArgKey("--replicas-max-per-node")]
        public DockerServiceCreateTask ReplicasMaxPerNode(ulong replicasMaxPerNode)
        {
            WithArgumentsKeyFromAttribute(replicasMaxPerNode.ToString());
            return this;
        }

        /// <summary>
        /// Reserve CPUs
        /// </summary>
        [ArgKey("--reserve-cpu")]
        public DockerServiceCreateTask ReserveCpu(decimal reserveCpu)
        {
            WithArgumentsKeyFromAttribute(reserveCpu.ToString());
            return this;
        }

        /// <summary>
        /// Reserve Memory
        /// </summary>
        [ArgKey("--reserve-memory")]
        public DockerServiceCreateTask ReserveMemory(string reserveMemory)
        {
            WithArgumentsKeyFromAttribute(reserveMemory.ToString());
            return this;
        }

        /// <summary>
        /// Restart when condition is met ("none"|"on-failure"|"any") (default "any")
        /// </summary>
        [ArgKey("--restart-condition")]
        public DockerServiceCreateTask RestartCondition(string restartCondition)
        {
            WithArgumentsKeyFromAttribute(restartCondition.ToString());
            return this;
        }

        /// <summary>
        /// Delay between restart attempts (ns|us|ms|s|m|h) (default 5s)
        /// </summary>
        [ArgKey("--restart-delay")]
        public DockerServiceCreateTask RestartDelay(string restartDelay)
        {
            WithArgumentsKeyFromAttribute(restartDelay.ToString());
            return this;
        }

        /// <summary>
        /// Maximum number of restarts before giving up
        /// </summary>
        [ArgKey("--restart-max-attempts")]
        public DockerServiceCreateTask RestartMaxAttempts(uint restartMaxAttempts)
        {
            WithArgumentsKeyFromAttribute(restartMaxAttempts.ToString());
            return this;
        }

        /// <summary>
        /// Window used to evaluate the restart policy (ns|us|ms|s|m|h)
        /// </summary>
        [ArgKey("--restart-window")]
        public DockerServiceCreateTask RestartWindow(string restartWindow)
        {
            WithArgumentsKeyFromAttribute(restartWindow.ToString());
            return this;
        }

        /// <summary>
        /// Delay between task rollbacks (ns|us|ms|s|m|h) (default 0s)
        /// </summary>
        [ArgKey("--rollback-delay")]
        public DockerServiceCreateTask RollbackDelay(string rollbackDelay)
        {
            WithArgumentsKeyFromAttribute(rollbackDelay.ToString());
            return this;
        }

        /// <summary>
        /// Action on rollback failure ("pause"|"continue") (default "pause")
        /// </summary>
        [ArgKey("--rollback-failure-action")]
        public DockerServiceCreateTask RollbackFailureAction(string rollbackFailureAction)
        {
            WithArgumentsKeyFromAttribute(rollbackFailureAction.ToString());
            return this;
        }

        /// <summary>
        /// Failure rate to tolerate during a rollback (default 0)
        /// </summary>
        [ArgKey("--rollback-max-failure-ratio")]
        public DockerServiceCreateTask RollbackMaxFailureRatio(float rollbackMaxFailureRatio)
        {
            WithArgumentsKeyFromAttribute(rollbackMaxFailureRatio.ToString());
            return this;
        }

        /// <summary>
        /// Duration after each task rollback to monitor for failure (ns|us|ms|s|m|h) (default 5s)
        /// </summary>
        [ArgKey("--rollback-monitor")]
        public DockerServiceCreateTask RollbackMonitor(string rollbackMonitor)
        {
            WithArgumentsKeyFromAttribute(rollbackMonitor.ToString());
            return this;
        }

        /// <summary>
        /// Rollback order ("start-first"|"stop-first") (default "stop-first")
        /// </summary>
        [ArgKey("--rollback-order")]
        public DockerServiceCreateTask RollbackOrder(string rollbackOrder)
        {
            WithArgumentsKeyFromAttribute(rollbackOrder.ToString());
            return this;
        }

        /// <summary>
        /// Maximum number of tasks rolled back simultaneously (0 to roll back all at once)
        /// </summary>
        [ArgKey("--rollback-parallelism")]
        public DockerServiceCreateTask RollbackParallelism(ulong rollbackParallelism)
        {
            WithArgumentsKeyFromAttribute(rollbackParallelism.ToString());
            return this;
        }

        /// <summary>
        /// Specify secrets to expose to the service
        /// </summary>
        [ArgKey("--secret")]
        public DockerServiceCreateTask Secret(string secret)
        {
            WithArgumentsKeyFromAttribute(secret.ToString());
            return this;
        }

        /// <summary>
        /// Time to wait before force killing a container (ns|us|ms|s|m|h) (default 10s)
        /// </summary>
        [ArgKey("--stop-grace-period")]
        public DockerServiceCreateTask StopGracePeriod(string stopGracePeriod)
        {
            WithArgumentsKeyFromAttribute(stopGracePeriod.ToString());
            return this;
        }

        /// <summary>
        /// Signal to stop the container
        /// </summary>
        [ArgKey("--stop-signal")]
        public DockerServiceCreateTask StopSignal(string stopSignal)
        {
            WithArgumentsKeyFromAttribute(stopSignal.ToString());
            return this;
        }

        /// <summary>
        /// Sysctl options
        /// </summary>
        [ArgKey("--sysctl")]
        public DockerServiceCreateTask Sysctl(string sysctl)
        {
            WithArgumentsKeyFromAttribute(sysctl.ToString());
            return this;
        }

        /// <summary>
        /// Allocate a pseudo-TTY
        /// </summary>
        [ArgKey("--tty")]
        public DockerServiceCreateTask Tty()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Delay between updates (ns|us|ms|s|m|h) (default 0s)
        /// </summary>
        [ArgKey("--update-delay")]
        public DockerServiceCreateTask UpdateDelay(string updateDelay)
        {
            WithArgumentsKeyFromAttribute(updateDelay.ToString());
            return this;
        }

        /// <summary>
        /// Action on update failure ("pause"|"continue"|"rollback") (default "pause")
        /// </summary>
        [ArgKey("--update-failure-action")]
        public DockerServiceCreateTask UpdateFailureAction(string updateFailureAction)
        {
            WithArgumentsKeyFromAttribute(updateFailureAction.ToString());
            return this;
        }

        /// <summary>
        /// Failure rate to tolerate during an update (default 0)
        /// </summary>
        [ArgKey("--update-max-failure-ratio")]
        public DockerServiceCreateTask UpdateMaxFailureRatio(float updateMaxFailureRatio)
        {
            WithArgumentsKeyFromAttribute(updateMaxFailureRatio.ToString());
            return this;
        }

        /// <summary>
        /// Duration after each task update to monitor for failure (ns|us|ms|s|m|h) (default 5s)
        /// </summary>
        [ArgKey("--update-monitor")]
        public DockerServiceCreateTask UpdateMonitor(string updateMonitor)
        {
            WithArgumentsKeyFromAttribute(updateMonitor.ToString());
            return this;
        }

        /// <summary>
        /// Update order ("start-first"|"stop-first") (default "stop-first")
        /// </summary>
        [ArgKey("--update-order")]
        public DockerServiceCreateTask UpdateOrder(string updateOrder)
        {
            WithArgumentsKeyFromAttribute(updateOrder.ToString());
            return this;
        }

        /// <summary>
        /// Maximum number of tasks updated simultaneously (0 to update all at once)
        /// </summary>
        [ArgKey("--update-parallelism")]
        public DockerServiceCreateTask UpdateParallelism(ulong updateParallelism)
        {
            WithArgumentsKeyFromAttribute(updateParallelism.ToString());
            return this;
        }

        /// <summary>
        /// Username or UID (format: <name|uid>[:<group|gid>])
        /// </summary>
        [ArgKey("--user")]
        public DockerServiceCreateTask User(string user)
        {
            WithArgumentsKeyFromAttribute(user.ToString());
            return this;
        }

        /// <summary>
        /// Send registry authentication details to swarm agents
        /// </summary>
        [ArgKey("--with-registry-auth")]
        public DockerServiceCreateTask WithRegistryAuth()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Working directory inside the container
        /// </summary>
        [ArgKey("--workdir")]
        public DockerServiceCreateTask Workdir(string workdir)
        {
            WithArgumentsKeyFromAttribute(workdir.ToString());
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_image);
            WithArguments(_command);
            WithArguments(_arg);

            return base.DoExecute(context);
        }
    }
}