//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Service
{
    public partial class DockerServiceLogsTask : ExternalProcessTaskBase<int, DockerServiceLogsTask>
    {
        private string _service;


        public DockerServiceLogsTask(string service)
        {
            ExecutablePath = "docker";
            WithArguments("service logs");
            _service = service;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Show extra details provided to logs
        /// </summary>
        [ArgKey("--details")]
        public DockerServiceLogsTask Details()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Follow log output
        /// </summary>
        [ArgKey("--follow")]
        public DockerServiceLogsTask Follow()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Do not map IDs to Names in output
        /// </summary>
        [ArgKey("--no-resolve")]
        public DockerServiceLogsTask NoResolve()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Do not include task IDs in output
        /// </summary>
        [ArgKey("--no-task-ids")]
        public DockerServiceLogsTask NoTaskIds()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Do not truncate output
        /// </summary>
        [ArgKey("--no-trunc")]
        public DockerServiceLogsTask NoTrunc()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Do not neatly format logs
        /// </summary>
        [ArgKey("--raw")]
        public DockerServiceLogsTask Raw()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        /// <summary>
        /// Show logs since timestamp (e.g. 2013-01-02T13:23:37) or relative (e.g. 42m for 42 minutes)
        /// </summary>
        [ArgKey("--since")]
        public DockerServiceLogsTask Since(string since)
        {
            WithArgumentsKeyFromAttribute(since.ToString());
            return this;
        }

        /// <summary>
        /// Number of lines to show from the end of the logs
        /// </summary>
        [ArgKey("--tail")]
        public DockerServiceLogsTask Tail(string tail)
        {
            WithArgumentsKeyFromAttribute(tail.ToString());
            return this;
        }

        /// <summary>
        /// Show timestamps
        /// </summary>
        [ArgKey("--timestamps")]
        public DockerServiceLogsTask Timestamps()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_service);

            return base.DoExecute(context);
        }
    }
}