//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Network
{
    public partial class DockerNetworkInspectTask : ExternalProcessTaskBase<int, DockerNetworkInspectTask>
    {
        private string[] _network;


        public DockerNetworkInspectTask(params string[] network)
        {
            ExecutablePath = "docker";
            WithArguments("network inspect");
            _network = network;
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Format the output using the given Go template
        /// </summary>
        [ArgKey("--format")]
        public DockerNetworkInspectTask Format(string format)
        {
            WithArgumentsKeyFromAttribute(format.ToString());
            return this;
        }

        /// <summary>
        /// Verbose output for diagnostics
        /// </summary>
        [ArgKey("--verbose")]
        public DockerNetworkInspectTask Verbose()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            WithArguments(_network);

            return base.DoExecute(context);
        }
    }
}