//-----------------------------------------------------------------------
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Text;
using FlubuCore.Context;
using FlubuCore.Tasks;
using FlubuCore.Tasks.Attributes;
using FlubuCore.Tasks.Process;

namespace FlubuCore.Tasks.Docker.Network
{
    public partial class DockerNetworkPruneTask : ExternalProcessTaskBase<int, DockerNetworkPruneTask>
    {
        public DockerNetworkPruneTask()
        {
            ExecutablePath = "docker";
            WithArguments("network prune");
        }

        protected override string Description { get; set; }

        /// <summary>
        /// Provide filter values (e.g. 'until=<timestamp>')
        /// </summary>
        [ArgKey("--filter")]
        public DockerNetworkPruneTask Filter(string filter)
        {
            WithArgumentsKeyFromAttribute(filter.ToString());
            return this;
        }

        /// <summary>
        /// Do not prompt for confirmation
        /// </summary>
        [ArgKey("--force")]
        public DockerNetworkPruneTask Force()
        {
            WithArgumentsKeyFromAttribute();
            return this;
        }

        protected override int DoExecute(ITaskContextInternal context)
        {
            return base.DoExecute(context);
        }
    }
}